//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adv
    {
        public string id { get; set; }
        public string advName { get; set; }
        public string advImage { get; set; }
        public string advLink { get; set; }
        public Nullable<int> advType { get; set; }
        public Nullable<int> advOrder { get; set; }
        public string advNote { get; set; }
        public string advLang { get; set; }
        public Nullable<bool> advActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string refId { get; set; }
    }
}
