//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string id { get; set; }
        public string fullName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string addresss { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string wardId { get; set; }
        public string districtId { get; set; }
        public string provinceId { get; set; }
    }
}
