//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string id { get; set; }
        public string pro_name { get; set; }
        public string pro_key { get; set; }
        public Nullable<int> pro_view { get; set; }
        public Nullable<int> proOrder { get; set; }
        public string proAvata { get; set; }
        public string acreage { get; set; }
        public string type { get; set; }
        public string place { get; set; }
        public string unit { get; set; }
        public string proFile { get; set; }
        public string desPro { get; set; }
        public string proContentTab1 { get; set; }
        public string proContentTab2 { get; set; }
        public string introContent { get; set; }
        public Nullable<bool> pro_home { get; set; }
        public Nullable<bool> pro_hot { get; set; }
        public Nullable<bool> active { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string pLang { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
