//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<int> number { get; set; }
        public string contents { get; set; }
        public string lang { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
