//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public string id { get; set; }
        public Nullable<int> sType { get; set; }
        public string nick { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string addresss { get; set; }
        public string fullName { get; set; }
        public Nullable<int> numberOder { get; set; }
    }
}
