//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhyChooseUss
    {
        public string id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string contents { get; set; }
        public Nullable<bool> active { get; set; }
        public string slang { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> numberOder { get; set; }
    }
}
