//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Oderdts = new HashSet<Oderdt>();
        }
    
        public string id { get; set; }
        public string brandId { get; set; }
        public string proCode { get; set; }
        public string pro_name { get; set; }
        public string pro_key { get; set; }
        public Nullable<int> proPrice { get; set; }
        public Nullable<int> proPrice_sale { get; set; }
        public Nullable<int> pro_view { get; set; }
        public Nullable<int> proOrder { get; set; }
        public string proAvata { get; set; }
        public string proImages5 { get; set; }
        public string proImages4 { get; set; }
        public string proImages3 { get; set; }
        public string proImages2 { get; set; }
        public string proImages1 { get; set; }
        public string proFile { get; set; }
        public string proContentTab3 { get; set; }
        public string proContentTab2 { get; set; }
        public string proContentTab1 { get; set; }
        public string prodescription { get; set; }
        public Nullable<bool> pro_hot { get; set; }
        public Nullable<bool> pro_new { get; set; }
        public Nullable<bool> active { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string pLang { get; set; }
        public string pTag { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string groupId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oderdt> Oderdts { get; set; }
    }
}
