//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adv
    {
        public int id { get; set; }
        public string advName { get; set; }
        public string images { get; set; }
        public string link { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> atype { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string advLang { get; set; }
        public Nullable<int> advOrder { get; set; }
        public string note { get; set; }
        public string siteTPA { get; set; }
        public string advTag { get; set; }
        public string imagesId { get; set; }
    }
}
