//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.News = new HashSet<News>();
            this.Products = new HashSet<Product>();
            this.ProductExtens = new HashSet<ProductExten>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string keys { get; set; }
        public Nullable<int> ctype { get; set; }
        public Nullable<bool> activeHome { get; set; }
        public Nullable<bool> active { get; set; }
        public string cateLang { get; set; }
        public string cateLevel { get; set; }
        public string catenote { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string cateAvata { get; set; }
        public string cateImg { get; set; }
        public Nullable<int> cateOrder { get; set; }
        public string cateImg_des { get; set; }
        public Nullable<int> catepar_id { get; set; }
        public Nullable<int> cate_cap { get; set; }
        public string siteTPA { get; set; }
        public string cateAvataId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductExten> ProductExtens { get; set; }
    }
}
