//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int id { get; set; }
        public string hotLine { get; set; }
        public string phone { get; set; }
        public string Email_Inbox { get; set; }
        public string shopemail { get; set; }
        public string emailpass { get; set; }
        public string addres { get; set; }
        public string shopname { get; set; }
        public string logobottom { get; set; }
        public string logotop { get; set; }
        public string fax { get; set; }
        public string google { get; set; }
        public string twiter { get; set; }
        public string youTube { get; set; }
        public string faceBook { get; set; }
        public string link { get; set; }
        public string Footer { get; set; }
        public string conTact { get; set; }
        public string map { get; set; }
        public string liveChat { get; set; }
        public Nullable<bool> active { get; set; }
        public string ex1 { get; set; }
        public string ex2 { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string conLang { get; set; }
        public string conMail_Port { get; set; }
        public string viewPro { get; set; }
        public string viewNews { get; set; }
        public string viewVideo { get; set; }
        public string viewYkien { get; set; }
        public Nullable<int> viewCountFrom { get; set; }
        public Nullable<int> viewCountTo { get; set; }
        public Nullable<int> viewNowFrom { get; set; }
        public Nullable<int> viewNowTo { get; set; }
        public string siteTPA { get; set; }
        public string googleAnalytics { get; set; }
        public string yeuCauBaoGia { get; set; }
        public string banCanHoTro { get; set; }
    }
}
