//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public Nullable<int> cusid { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string addressIn { get; set; }
        public string address { get; set; }
        public string shiping { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<bool> active { get; set; }
        public string conLang { get; set; }
        public string siteTPA { get; set; }
        public Nullable<int> type { get; set; }
    }
}
