//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public Nullable<int> par_id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> mtype { get; set; }
        public string mtypeOf { get; set; }
        public string note { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public Nullable<int> mOrder { get; set; }
        public string ex1 { get; set; }
        public Nullable<int> mcap { get; set; }
        public string mLang { get; set; }
        public Nullable<int> mPosition { get; set; }
        public string siteTPA { get; set; }
    }
}
