//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public Nullable<int> groupid { get; set; }
        public string images { get; set; }
        public string title { get; set; }
        public string descript { get; set; }
        public string contents { get; set; }
        public Nullable<int> ntype { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string new_key { get; set; }
        public string ex1 { get; set; }
        public string ex2 { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public Nullable<int> newOrder { get; set; }
        public Nullable<int> viewCount { get; set; }
        public string newLang { get; set; }
        public string siteTPA { get; set; }
        public string imagesId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
