//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oderdt
    {
        public int id { get; set; }
        public Nullable<int> oderid { get; set; }
        public Nullable<int> proid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> priceNow { get; set; }
        public Nullable<double> priceCount { get; set; }
    
        public virtual Oder Oder { get; set; }
        public virtual Product Product { get; set; }
    }
}
