//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteChildent
    {
        public int id { get; set; }
        public string siteName { get; set; }
        public string siteLang { get; set; }
        public string siteImg { get; set; }
        public Nullable<int> siteOrder { get; set; }
        public Nullable<bool> siteActive { get; set; }
        public string siteExten { get; set; }
    }
}
