//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int id { get; set; }
        public Nullable<bool> stype { get; set; }
        public string nick { get; set; }
        public string phone { get; set; }
        public string fullname { get; set; }
        public string sLang { get; set; }
        public string siteTPA { get; set; }
    }
}
