//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WEBTPAEntities : DbContext
    {
        public WEBTPAEntities()
            : base("name=WEBTPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Adv> Advs { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categorys { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Oderdt> Oderdts { get; set; }
        public virtual DbSet<Oder> Oders { get; set; }
        public virtual DbSet<SiteChildent> SiteChildents { get; set; }
        public virtual DbSet<Support> Supports { get; set; }
        public virtual DbSet<Tagpro> Tagproes { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductExten> ProductExtens { get; set; }
        public virtual DbSet<Ykien> Ykiens { get; set; }
    
        public virtual ObjectResult<sp_Config_SelectSeoOk_Result> sp_Config_SelectSeoOk(string conLang, string site)
        {
            var conLangParameter = conLang != null ?
                new ObjectParameter("conLang", conLang) :
                new ObjectParameter("conLang", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Config_SelectSeoOk_Result>("sp_Config_SelectSeoOk", conLangParameter, siteParameter);
        }
    
        public virtual ObjectResult<sp_Config_SelectViewNumber_Result> sp_Config_SelectViewNumber(string conLang, string site)
        {
            var conLangParameter = conLang != null ?
                new ObjectParameter("conLang", conLang) :
                new ObjectParameter("conLang", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Config_SelectViewNumber_Result>("sp_Config_SelectViewNumber", conLangParameter, siteParameter);
        }
    }
}
