//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int vId { get; set; }
        public Nullable<int> cateId { get; set; }
        public string vName { get; set; }
        public string vKey { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string vLink { get; set; }
        public Nullable<int> vOrder { get; set; }
        public string vnote { get; set; }
        public string vimg { get; set; }
        public Nullable<int> cateView { get; set; }
        public string vLang { get; set; }
        public string siteTPA { get; set; }
    }
}
