//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productgold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ykien
    {
        public int yId { get; set; }
        public string AdminId { get; set; }
        public string ynote { get; set; }
        public string yName { get; set; }
        public string yEmailAdd { get; set; }
        public string yPhone { get; set; }
        public Nullable<System.DateTime> yCreateDate { get; set; }
        public Nullable<bool> yActive { get; set; }
        public Nullable<int> pId { get; set; }
    }
}
