//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oder()
        {
            this.Oderdts = new HashSet<Oderdt>();
        }
    
        public string id { get; set; }
        public string cusId { get; set; }
        public Nullable<int> realMoney { get; set; }
        public Nullable<int> totalMoney { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> priceShip { get; set; }
        public string noteSite { get; set; }
        public string noteSiteAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oderdt> Oderdts { get; set; }
    }
}
