//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public string id { get; set; }
        public string pName { get; set; }
        public string pImage { get; set; }
        public string pNote { get; set; }
        public Nullable<int> numberOder { get; set; }
        public string pLink { get; set; }
        public string groupId { get; set; }
        public string lang { get; set; }
    }
}
