//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string id { get; set; }
        public string hotLine { get; set; }
        public string phone { get; set; }
        public string email_Inbox { get; set; }
        public string email_Send { get; set; }
        public string emailPass { get; set; }
        public string addresss { get; set; }
        public string shopName { get; set; }
        public string logoBottom { get; set; }
        public string logoTop { get; set; }
        public string linkLogo { get; set; }
        public string copyright { get; set; }
        public string google { get; set; }
        public string twiter { get; set; }
        public string youTube { get; set; }
        public string faceBook { get; set; }
        public string homeVideo { get; set; }
        public string footer { get; set; }
        public string infoPage { get; set; }
        public string conTact { get; set; }
        public string map { get; set; }
        public string liveChat { get; set; }
        public string googleAdsense { get; set; }
        public string googleAnalytics { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public Nullable<int> mail_Port { get; set; }
        public Nullable<int> viewNewPageList { get; set; }
        public Nullable<int> viewNewPageDetail { get; set; }
        public Nullable<int> viewNewPageHome { get; set; }
        public Nullable<int> viewProPageHome { get; set; }
        public Nullable<int> viewProPageDetail { get; set; }
        public Nullable<int> viewProPageList { get; set; }
        public Nullable<int> viewLibPageList { get; set; }
        public string conLang { get; set; }
        public string zaloChat { get; set; }
        public string fbChat { get; set; }
        public string introStep1 { get; set; }
        public string introStep2 { get; set; }
        public string introStep3 { get; set; }
        public string introStep1R { get; set; }
        public string introStep2R { get; set; }
        public string introStep3R { get; set; }
        public Nullable<int> countRow1 { get; set; }
        public Nullable<int> countRow2 { get; set; }
        public Nullable<int> countRow3 { get; set; }
        public Nullable<int> countRow4 { get; set; }
        public string lableRow1 { get; set; }
        public string lableRow2 { get; set; }
        public string lableRow3 { get; set; }
        public string lableRow4 { get; set; }
        public string lableIntroName { get; set; }
        public string lableIntroDes { get; set; }
        public string lableSolutionName { get; set; }
        public string lableSolutionDes { get; set; }
        public string lableSayName { get; set; }
        public string lableSayDes { get; set; }
        public string lableWhyName { get; set; }
        public string lableWhyDes { get; set; }
        public string lablePartnerName { get; set; }
        public string lablePartnerDes { get; set; }
    }
}
