//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib
    {
        public string libId { get; set; }
        public string linName { get; set; }
        public string libKey { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string libLink { get; set; }
        public Nullable<int> libOrder { get; set; }
        public string libNote { get; set; }
        public string libImage { get; set; }
        public string libLang { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> libType { get; set; }
        public string cateId { get; set; }
    }
}
