//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string id { get; set; }
        public string groupId { get; set; }
        public string newImage { get; set; }
        public string title { get; set; }
        public string descript { get; set; }
        public string contents { get; set; }
        public string new_key { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string newLang { get; set; }
        public Nullable<int> newOrder { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<bool> newHot { get; set; }
        public Nullable<bool> newNew { get; set; }
        public string newFile { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
