//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string id { get; set; }
        public string hotLine { get; set; }
        public string phone { get; set; }
        public string email_Inbox { get; set; }
        public string email_Send { get; set; }
        public string emailPass { get; set; }
        public string addresss { get; set; }
        public string shopName { get; set; }
        public string logoBottom { get; set; }
        public string logoTop { get; set; }
        public string fax { get; set; }
        public string google { get; set; }
        public string twiter { get; set; }
        public string youTube { get; set; }
        public string faceBook { get; set; }
        public string linkLogo { get; set; }
        public string homeVideo { get; set; }
        public string footer { get; set; }
        public string conTact { get; set; }
        public string map { get; set; }
        public string liveChat { get; set; }
        public string googleAdsense { get; set; }
        public string googleAnalytics { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public Nullable<int> mail_Port { get; set; }
        public Nullable<int> viewNewPageList { get; set; }
        public Nullable<int> viewNewPageDetail { get; set; }
        public Nullable<int> viewNewPageHome { get; set; }
        public Nullable<int> viewProPageHome { get; set; }
        public Nullable<int> viewProPageDetail { get; set; }
        public Nullable<int> viewProPageList { get; set; }
        public Nullable<int> viewLibPageList { get; set; }
        public Nullable<int> priceShip { get; set; }
        public string conLang { get; set; }
        public string mapHN { get; set; }
        public string mapHCM { get; set; }
        public string infoHCM { get; set; }
        public string infoHN { get; set; }
        public string infoPage { get; set; }
        public string bgNews { get; set; }
        public string bgMenu { get; set; }
        public string bgProduct { get; set; }
        public string zaloChat { get; set; }
        public string fbChat { get; set; }
    }
}
