//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int langId { get; set; }
        public string langCode { get; set; }
        public string langName { get; set; }
        public string langImg { get; set; }
        public Nullable<bool> langDefault { get; set; }
    }
}
