//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuTruyCap
    {
        public string id { get; set; }
        public int viewDay { get; set; }
        public int viewMonth { get; set; }
        public int viewYear { get; set; }
        public int countTotal { get; set; }
    }
}
