//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string id { get; set; }
        public string hotLine { get; set; }
        public string phone { get; set; }
        public string email_Inbox { get; set; }
        public string email_Send { get; set; }
        public string emailPass { get; set; }
        public Nullable<int> mail_Port { get; set; }
        public string addresss { get; set; }
        public string shopName { get; set; }
        public string logoTop { get; set; }
        public string logoBottom { get; set; }
        public string linkLogo { get; set; }
        public string copyRight { get; set; }
        public string google { get; set; }
        public string twiter { get; set; }
        public string youTube { get; set; }
        public string faceBook { get; set; }
        public string tiki { get; set; }
        public string shoppe { get; set; }
        public string zaloChat { get; set; }
        public string homeVideo { get; set; }
        public string footer { get; set; }
        public string conTact { get; set; }
        public string liveChat { get; set; }
        public string googleAdsense { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public Nullable<int> viewNewPageList { get; set; }
        public Nullable<int> viewNewPageDetail { get; set; }
        public Nullable<int> viewNewPageHome { get; set; }
        public Nullable<int> viewProPageHome { get; set; }
        public Nullable<int> viewProPageDetail { get; set; }
        public Nullable<int> viewProPageList { get; set; }
        public Nullable<int> priceShip { get; set; }
        public string conLang { get; set; }
        public string mapBig { get; set; }
        public string infoPage { get; set; }
        public string favicon { get; set; }
        public string langDefault { get; set; }
        public Nullable<int> viewProBy { get; set; }
        public Nullable<bool> viewPercen { get; set; }
        public Nullable<int> viewPrice { get; set; }
        public Nullable<int> typeSendMail { get; set; }
        public string introService { get; set; }
        public string introWhychoose { get; set; }
        public string introFAQ { get; set; }
        public string titleService { get; set; }
        public string titleWhychoose { get; set; }
        public string titleFAQ { get; set; }
        public string titlePrice { get; set; }
        public string titlePriceSub1 { get; set; }
        public string titlePriceSub2 { get; set; }
        public string titlePriceSub3 { get; set; }
        public string titlePriceSub4 { get; set; }
        public string linkPrice { get; set; }
        public string imgPrice { get; set; }
        public string imgFaq { get; set; }
        public string linkHDMH { get; set; }
        public string linkHDTT { get; set; }
    }
}
