//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tagpro
    {
        public string tagId { get; set; }
        public string tagName { get; set; }
        public string tagKey { get; set; }
        public Nullable<int> typeTag { get; set; }
        public Nullable<int> tagOrder { get; set; }
        public string lang { get; set; }
    }
}
