//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string id { get; set; }
        public string nameSub { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string mtypeOf { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string icon { get; set; }
        public string note { get; set; }
        public string mLang { get; set; }
        public Nullable<int> mOrder { get; set; }
        public string par_id { get; set; }
        public Nullable<int> mtype { get; set; }
        public Nullable<int> mcap { get; set; }
        public Nullable<int> mPosition { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string cateProductId { get; set; }
    }
}
