//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public string id { get; set; }
        public string name { get; set; }
        public string name_url { get; set; }
        public string titleSeo { get; set; }
        public string keySeo { get; set; }
        public string desSeo { get; set; }
        public string solutionDescription { get; set; }
        public string solutionDetail { get; set; }
        public string lang { get; set; }
        public Nullable<int> solutionOrder { get; set; }
        public Nullable<bool> solutionActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string solutionImage { get; set; }
        public string solutionIcon { get; set; }
    }
}
