//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSPRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oderdt
    {
        public string id { get; set; }
        public string oderId { get; set; }
        public string proId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> priceNow { get; set; }
        public Nullable<int> priceCount { get; set; }
    
        public virtual Oder Oder { get; set; }
    }
}
